apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-api
  namespace: ipam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipam-api
  template:
    metadata:
      labels:
        app: ipam-api
    spec:
      containers:
      - name: api
        image: ipam-api:dev-001  # Use your local image name
        imagePullPolicy: Never  # This prevents Kubernetes from trying to pull from a registry
        envFrom:
        - secretRef:
            name: pg-secret
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: ipam-api-key
              key: API_KEY
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /docs
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /docs
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: ipam-api
  namespace: ipam
spec:
  type: NodePort
  selector:
    app: ipam-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30080